/** @type {import('tailwindcss').Config} */
import daisyui from 'daisyui'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Cal Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      // Keep all original themes
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      
      // Add custom themes
      {
        "modern-purple": {
          "primary": "#8b5cf6",
          "primary-focus": "#7c3aed",
          "primary-content": "#ffffff",
          "secondary": "#ec4899",
          "secondary-focus": "#db2777",
          "secondary-content": "#ffffff",
          "accent": "#06b6d4",
          "accent-focus": "#0891b2",
          "accent-content": "#ffffff",
          "neutral": "#1f2937",
          "neutral-focus": "#111827",
          "neutral-content": "#f3f4f6",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#f3f4f6",
          "base-content": "#1f2937",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },
        
        "ocean-blue": {
          "primary": "#0ea5e9",
          "primary-focus": "#0284c7",
          "primary-content": "#ffffff",
          "secondary": "#06b6d4",
          "secondary-focus": "#0891b2",
          "secondary-content": "#ffffff",
          "accent": "#8b5cf6",
          "accent-focus": "#7c3aed",
          "accent-content": "#ffffff",
          "neutral": "#0f172a",
          "neutral-focus": "#020617",
          "neutral-content": "#f1f5f9",
          "base-100": "#ffffff",
          "base-200": "#f8fafc",
          "base-300": "#f1f5f9",
          "base-content": "#0f172a",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "1.25rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "1.9rem",
        },

        "dark-slate": {
          "primary": "#6366f1",
          "primary-focus": "#4f46e5",
          "primary-content": "#ffffff",
          "secondary": "#a855f7",
          "secondary-focus": "#9333ea",
          "secondary-content": "#ffffff",
          "accent": "#06b6d4",
          "accent-focus": "#0891b2",
          "accent-content": "#ffffff",
          "neutral": "#1e293b",
          "neutral-focus": "#0f172a",
          "neutral-content": "#f1f5f9",
          "base-100": "#0f172a",
          "base-200": "#1e293b",
          "base-300": "#334155",
          "base-content": "#f1f5f9",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },

        "midnight": {
          "primary": "#f472b6",
          "primary-focus": "#ec4899",
          "primary-content": "#ffffff",
          "secondary": "#a78bfa",
          "secondary-focus": "#8b5cf6",
          "secondary-content": "#ffffff",
          "accent": "#34d399",
          "accent-focus": "#10b981",
          "accent-content": "#ffffff",
          "neutral": "#1f2937",
          "neutral-focus": "#111827",
          "neutral-content": "#f9fafb",
          "base-100": "#111827",
          "base-200": "#1f2937",
          "base-300": "#374151",
          "base-content": "#f9fafb",
          "info": "#60a5fa",
          "success": "#34d399",
          "warning": "#fbbf24",
          "error": "#f87171",
          "--rounded-box": "1.5rem",
          "--rounded-btn": "1rem",
          "--rounded-badge": "1.9rem",
        },

        "coral": {
          "primary": "#fb923c",
          "primary-focus": "#f97316",
          "primary-content": "#ffffff",
          "secondary": "#f472b6",
          "secondary-focus": "#ec4899",
          "secondary-content": "#ffffff",
          "accent": "#06b6d4",
          "accent-focus": "#0891b2",
          "accent-content": "#ffffff",
          "neutral": "#292524",
          "neutral-focus": "#1c1917",
          "neutral-content": "#fafaf9",
          "base-100": "#fffbeb",
          "base-200": "#fef3c7",
          "base-300": "#fde68a",
          "base-content": "#292524",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "1rem",
          "--rounded-btn": "2rem",
          "--rounded-badge": "1.9rem",
        },

        "cyber-neon": {
          "primary": "#00ffff",
          "primary-focus": "#00d4d4",
          "primary-content": "#000000",
          "secondary": "#ff00ff",
          "secondary-focus": "#d400d4",
          "secondary-content": "#000000",
          "accent": "#00ff00",
          "accent-focus": "#00d400",
          "accent-content": "#000000",
          "neutral": "#1a1a2e",
          "neutral-focus": "#0f0f1e",
          "neutral-content": "#ffffff",
          "base-100": "#0f0f1e",
          "base-200": "#1a1a2e",
          "base-300": "#252538",
          "base-content": "#ffffff",
          "info": "#00d4ff",
          "success": "#00ff88",
          "warning": "#ffaa00",
          "error": "#ff0055",
          "--rounded-box": "0.25rem",
          "--rounded-btn": "0.25rem",
          "--rounded-badge": "0.25rem",
        },

        "alpine": {
          "primary": "#0284c7",
          "primary-focus": "#0369a1",
          "primary-content": "#ffffff",
          "secondary": "#64748b",
          "secondary-focus": "#475569",
          "secondary-content": "#ffffff",
          "accent": "#06b6d4",
          "accent-focus": "#0891b2",
          "accent-content": "#ffffff",
          "neutral": "#334155",
          "neutral-focus": "#1e293b",
          "neutral-content": "#f8fafc",
          "base-100": "#f8fafc",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "base-content": "#0f172a",
          "info": "#3b82f6",
          "success": "#10b981",
          "warning": "#f59e0b",
          "error": "#ef4444",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
        },

        "creative": {
          "primary": "#8b5cf6",
          "primary-focus": "#7c3aed",
          "primary-content": "#ffffff",
          "secondary": "#ec4899",
          "secondary-focus": "#db2777",
          "secondary-content": "#ffffff",
          "accent": "#f59e0b",
          "accent-focus": "#d97706",
          "accent-content": "#ffffff",
          "neutral": "#27272a",
          "neutral-focus": "#18181b",
          "neutral-content": "#fafafa",
          "base-100": "#fafafa",
          "base-200": "#f4f4f5",
          "base-300": "#e4e4e7",
          "base-content": "#18181b",
          "info": "#3b82f6",
          "success": "#22c55e",
          "warning": "#eab308",
          "error": "#ef4444",
          "--rounded-box": "1.5rem",
          "--rounded-btn": "1rem",
          "--rounded-badge": "1.9rem",
        },
      },
    ],
  },

  
}


